version: '3.9'
services:
  mysql_206:
    env_file:
      - .env
    container_name: mysql_206
    hostname: mysql_206
    image: mysql:5.7
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_206:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      TZ: America/Sao_Paulo
